# Generated by Django 5.1.3 on 2025-03-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorFeedback',
        ),
    ]
