# Generated by Django 5.1.3 on 2025-03-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_servicefeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceFeedback',
        ),
    ]
